apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage
spec:
  {{- if .Values.storageClassName }}
  storageClassName: {{ .Values.storageClassName }}
  {{- end }}
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi