apiVersion: v1
items:
- apiVersion: v1
  data:
    60-lower.cnf: |
      [mysqld]
      lower_case_table_names=1
  kind: ConfigMap
  metadata:
    labels:
      db: mysql
      template: mysql-persistent-template
    name: mysql-lower-map
- apiVersion: v1
  data:
    70-sqlmode.cnf: |
      [mysqld]
      sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
  kind: ConfigMap
  metadata:
    labels:
      db: mysql
      template: mysql-persistent-template
    name: mysql-sqlmode-map
- apiVersion: v1
  kind: Secret
  metadata:
    annotations:
      template.openshift.io/expose-database_name: '{.data[''database-name'']}'
      template.openshift.io/expose-password: '{.data[''database-password'']}'
      template.openshift.io/expose-root_password: '{.data[''database-root-password'']}'
      template.openshift.io/expose-username: '{.data[''database-user'']}'
    labels:
      db: mysql
      template: mysql-persistent-template
    name: mysql
  stringData:
    database-name: mydb
    database-password: mysql
    database-root-password: mysql
    database-user: mysql
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      template.openshift.io/expose-uri: mysql://{.spec.clusterIP}:{.spec.ports[?(.name=="mysql")].port}
    labels:
      db: mysql
      template: mysql-persistent-template
    name: mysql
  spec:
    ports:
    - name: mysql
      port: 3306
    selector:
      name: mysql
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      db: mysql
      template: mysql-persistent-template
    name: mysql
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true"
    labels:
      db: mysql
      template: mysql-persistent-template
    name: mysql
  spec:
    replicas: 1
    selector:
      name: mysql
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: mysql
      spec:
        containers:
        - env:
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                key: database-user
                name: mysql
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-password
                name: mysql
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-root-password
                name: mysql
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                key: database-name
                name: mysql
          - name: MYSQL_COLLATION
            value: utf8_general_ci
          - name: MYSQL_CHARSET
            value: utf8
          image: ' '
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -i
              - -c
              - MYSQL_PWD="$MYSQL_PASSWORD" mysqladmin -u $MYSQL_USER ping
            initialDelaySeconds: 180
            timeoutSeconds: 1
          name: mysql
          ports:
          - containerPort: 3306
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -i
              - -c
              - MYSQL_PWD="$MYSQL_PASSWORD" mysqladmin -u $MYSQL_USER ping
            initialDelaySeconds: 180
            timeoutSeconds: 1
          resources:
            limits:
              memory: 512Mi
          volumeMounts:
          - mountPath: /var/lib/mysql/data
            name: mysql-data
          - mountPath: /etc/my.cnf.d/60-lower.cnf
            name: mylowercnf
            subPath: 60-lower.cnf
          - mountPath: /etc/my.cnf.d/70-sqlmode.cnf
            name: mysqlmodecnf
            subPath: 70-sqlmode.cnf
        volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql
        - configMap:
            defaultMode: 420
            items:
            - key: 60-lower.cnf
              path: 60-lower.cnf
            name: mysql-lower-map
          name: mylowercnf
        - configMap:
            defaultMode: 420
            items:
            - key: 70-sqlmode.cnf
              path: 70-sqlmode.cnf
            name: mysql-sqlmode-map
          name: mysqlmodecnf
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - mysql
        from:
          kind: ImageStreamTag
          name: mysql:8.0-el8
          namespace: openshift
      type: ImageChange
    - type: ConfigChange
kind: List
metadata: {}